# Input — mirrors niri cfg/input.kdl

repeat_rate=25
repeat_delay=600
numlockon=1
xkb_rules_layout=us
xkb_rules_variant=altgr-intl
xkb_rules_options=caps:swapescape

tap_to_click=1
trackpad_natural_scrolling=1
trackpad_accel_speed=0.2

sloppyfocus=1
view_current_to_back=1
