# Misc env / cursor — mirrors niri cfg/misc.kdl

env=ELECTRON_OZONE_PLATFORM_HINT,auto
env=QT_QPA_PLATFORM,wayland
env=QT_QPA_PLATFORMTHEME,gtk3
env=QT_QPA_PLATFORMTHEME_QT6,gtk3
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=XDG_CURRENT_DESKTOP,mango
env=NIXOS_OZONE_WL,1

cursor_size=24
cursor_hide_on_keypress=1
cursor_hide_timeout=5

focus_on_activate=1
allow_shortcuts_inhibit=1
drag_tile_to_tile=1
