[onedrive]
type = webdav
url = https://itisvolta-my.sharepoint.com/personal/lorenzo_baracco_volta-alessandria_it1/Documents
vendor = other
user = lorenzo.baracco@volta-alessandria.it
pass = X2Rd92f-80mbT3djibe2Qm9g3fOJ2xVP
filter_from = /home/lorenzo/.config/rclone/filters.txt
