	{
  description = "My NixOS configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    niri-flake = {
      url = "github:sodiboo/niri-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    silentSDDM = {
      url = "github:uiriansan/SilentSDDM";
      inputs.nixpkgs.follows = "nixpkgs";
    };

  };

  outputs = { self, nixpkgs, home-manager, niri-flake, silentSDDM, ... }@inputs:
  let
    system = "x86_64-linux";
  in {
    nixosConfigurations."nixlorenzo" = nixpkgs.lib.nixosSystem {  
      inherit system;
      specialArgs = { inherit inputs; };
      modules = [
        ./hardware-configuration.nix   # generated by nixos-generate-config
        ./configuration.nix
        niri-flake.nixosModules.niri
        silentSDDM.nixosModules.default
        home-manager.nixosModules.home-manager
        {
          home-manager.useGlobalPkgs   = true;
          home-manager.useUserPackages = true;
          home-manager.users.lorenzo = import ./home.nix; 
          home-manager.extraSpecialArgs = { inherit inputs; };
          home-manager.backupFileExtension = "bak";

        }
      ];
    };
  };
}
